MD-77 || CI Configuration for generating pr builds
readytowork-org/flutter-skeleton pull request #1
Opened 2023-06-02 05:36 UTC by creativeprashant007

2023-06-02 08:36 UTC, creativeprashant007 commented
Me too

2023-06-02 08:43 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 08:44 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 08:49 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 08:56 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 08:56 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 08:56 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 09:02 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 09:10 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 09:18 UTC, creativeprashant007 commented
Comment Api Tested Successfully

2023-06-02 09:28 UTC, creativeprashant007 commented
This is test comment

2023-06-02 09:28 UTC, creativeprashant007 commented
This is test comment

2023-06-02 09:29 UTC, creativeprashant007 commented
This is test comment

2023-06-02 10:37 UTC, creativeprashant007 commented
This is test comment

2023-06-02 10:52 UTC, creativeprashant007 commented
This is test comment

2023-06-02 11:07 UTC, creativeprashant007 commented
build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

2023-06-02 11:19 UTC, creativeprashant007 commented
Click [here](https://example.com/my-artifact) to access the artifact.

2023-06-02 11:41 UTC, creativeprashant007 commented
Click [here](https://circleci.com/api/v1.1/project/github/readytowork-org/flutter-skeleton/41/artifacts/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to access the artifact.

2023-06-05 06:07 UTC, creativeprashant007 commented
Click [here](https://circleci.com/api/v1.1/project/github/readytowork-org/flutter-skeleton/42/artifacts/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to access the artifact.

2023-06-05 11:18 UTC, creativeprashant007 commented
Click [here](https:///output/job/7930c78d-6e60-453a-ab24-2dad3d53a901/artifacts/0/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to access the artifact.

2023-06-05 11:29 UTC, creativeprashant007 commented
Click [here](https://output.circle-artifacts.com/output/job/6200f8b9-059b-4860-b0a6-b7a66010150e/artifacts/0/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to access the artifact.

2023-06-05 11:34 UTC, sawal-timsina commented on lib/config.dart.example
@creativeprashant007  revert this please

2023-06-05 11:38 UTC, creativeprashant007 commented
Click [here](https://output.circle-artifacts.com/output/job/49206fef-9fa4-41b8-9442-0aa1c7655ba4/artifacts/0/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to download the app.

2023-06-05 11:46 UTC, creativeprashant007 commented
Click [here](https://output.circle-artifacts.com/output/job/b71196df-03a8-4006-aa19-49dc353ae425/artifacts/0/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk) to download the app.

2023-06-08 04:42 UTC, sawal-timsina commented on .circleci/config.yml
> +            flutter build apk --split-per-abi --release --build-name=$VERSION_CODE
@creativeprashant007  let's not split the apks, as it might not run on everyone's device

2023-06-08 05:08 UTC, sawal-timsina requested changes
Remove .example from config import
Remove firebase config
Add Branch name in app label

2023-06-08 09:19 UTC, creativeprashant007 commented
Click [here](https://output.circle-artifacts.com/output/job/0527be6e-bdfb-46bf-805c-f9f13ce8357c/artifacts/0/build/app/outputs/apk/release/app-release.apk) to download the app.

2023-06-08 10:52 UTC, creativeprashant007 commented
Click [here](https://output.circle-artifacts.com/output/job/fcf310f3-ed6b-4b5e-9fbb-27c5c7cb50ef/artifacts/0/build/app/outputs/apk/release/app-release.apk) to download the app.

2023-06-09 10:10 UTC, sawal-timsina approved these changes
LGTM

2023-06-09 10:26 UTC, closed without merging